#!/usr/bin/env bash
# multi_run.sh - Launch multiple Docker containers from different workspaces
#
# Usage:
#   ./multi_run.sh <path1> <path2> ...     # Start all
#   ./multi_run.sh --stop                  # Stop all
#   ./multi_run.sh --status                # Show running containers
#   ./multi_run.sh -h, --help              # Show help
#
# Generates a merged compose.yaml with resolved variables and unique
# service names. Supports same repo from different workspaces.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
GENERATED_COMPOSE="${SCRIPT_DIR}/../.multi_compose.yaml"
STATE_FILE="${SCRIPT_DIR}/../.multi_state"

_log() { printf "[multi] %s\n" "$*"; }
_error() { printf "[multi] ERROR: %s\n" "$*" >&2; exit 1; }

# ── Help ─────────────────────────────────────────────────────────────────────

usage() {
    cat >&2 <<'EOF'
Usage: multi_run.sh [OPTIONS] <path1> <path2> ...

Launch multiple Docker containers from different workspaces simultaneously.
Generates a merged compose with unique service names per instance.

Commands:
  <path1> <path2> ...   Start containers from given workspace Docker paths
  --stop                Stop all containers launched by multi_run
  --status              Show status of multi_run containers

Options:
  -h, --help            Show this help

Examples:
  # Different ws, different repos
  ./multi_run.sh ~/robot_ws/docker_ros_noetic ~/nav_ws/docker_ros2_humble

  # Same repo, different workspaces
  ./multi_run.sh ~/robot_a_ws/docker_ros_noetic ~/robot_b_ws/docker_ros_noetic

  # Stop all
  ./multi_run.sh --stop
EOF
    exit 0
}

# ── Unique ID from path ──────────────────────────────────────────────────────

_path_id() {
    # Generate a short unique ID from workspace path
    # e.g. /home/user/robot_ws/docker_ros_noetic → ros_noetic_a1b2
    local abs_path="$1"
    local image_name
    image_name=$(grep -oP 'IMAGE_NAME=\K.*' "${abs_path}/.env" 2>/dev/null || basename "${abs_path}")
    local hash
    hash=$(echo "${abs_path}" | md5sum | cut -c1-4)
    echo "${image_name}_${hash}"
}

# ── Generate merged compose ──────────────────────────────────────────────────

_generate_compose() {
    local paths=("$@")

    # Start YAML
    cat > "${GENERATED_COMPOSE}" <<'HEADER'
# Auto-generated by multi_run.sh — do not edit
services:
HEADER

    : > "${STATE_FILE}"

    for p in "${paths[@]}"; do
        local abs_path
        abs_path="$(cd "${p}" && pwd -P)"

        [[ -f "${abs_path}/compose.yaml" ]] || _error "No compose.yaml in ${abs_path}"

        # Ensure .env exists
        if [[ ! -f "${abs_path}/.env" ]]; then
            _log "Generating .env for ${abs_path}..."
            if [[ -f "${abs_path}/docker_template/setup.sh" ]]; then
                "${abs_path}/docker_template/setup.sh" --base-path "${abs_path}"
            else
                _error "No .env and no setup.sh in ${abs_path}"
            fi
        fi

        local instance_id
        instance_id="$(_path_id "${abs_path}")"

        # Resolve compose (expand all variables)
        local resolved
        resolved=$(cd "${abs_path}" && docker compose --env-file .env config 2>/dev/null) \
            || _error "Failed to resolve compose in ${abs_path}"

        # Extract devel service, rename, remove container_name, append
        echo "${resolved}" | python3 -c "
import sys, yaml

data = yaml.safe_load(sys.stdin)
services = data.get('services', {})

# Only include devel service (not test/runtime)
if 'devel' not in services:
    print(f'  # WARN: no devel service in input', file=sys.stderr)
    sys.exit(0)

svc = services['devel']

# Remove container_name (let compose auto-name)
svc.pop('container_name', None)

# Remove deploy section if it causes issues
# Keep it — GPU support needed

# Rename service
new_name = '${instance_id}'
output = {new_name: svc}

# Output as YAML (indented for services: block)
import io
stream = io.StringIO()
yaml.dump(output, stream, default_flow_style=False, allow_unicode=True)
for line in stream.getvalue().splitlines():
    print(f'  {line}')
" >> "${GENERATED_COMPOSE}"

        echo "${abs_path}" >> "${STATE_FILE}"
        _log "Added: ${abs_path} → service: ${instance_id}"
    done

    _log "Generated: ${GENERATED_COMPOSE}"
}

# ── Start ────────────────────────────────────────────────────────────────────

_start() {
    local paths=("$@")
    _generate_compose "${paths[@]}"

    # xhost
    for p in "${paths[@]}"; do
        local abs_path
        abs_path="$(cd "${p}" && pwd -P)"
        local user_name
        user_name=$(grep -oP 'USER_NAME=\K.*' "${abs_path}/.env" 2>/dev/null || true)
        if [[ -n "${user_name}" ]]; then
            if [[ "${XDG_SESSION_TYPE:-x11}" == "wayland" ]]; then
                xhost "+SI:localuser:${user_name}" >/dev/null 2>&1 || true
            else
                xhost +local: >/dev/null 2>&1 || true
            fi
        fi
    done

    _log "Starting ${#paths[@]} containers..."
    docker compose -f "${GENERATED_COMPOSE}" up -d
    _log "All containers started. Use --stop to stop them."
}

# ── Stop ─────────────────────────────────────────────────────────────────────

_stop() {
    if [[ ! -f "${GENERATED_COMPOSE}" ]]; then
        _error "No running multi_run session found"
    fi

    _log "Stopping all containers..."
    docker compose -f "${GENERATED_COMPOSE}" down
    rm -f "${GENERATED_COMPOSE}" "${STATE_FILE}"
    _log "All containers stopped."
}

# ── Status ───────────────────────────────────────────────────────────────────

_status() {
    if [[ ! -f "${GENERATED_COMPOSE}" ]]; then
        _log "No running multi_run session."
        return 0
    fi

    _log "Active workspaces:"
    while IFS= read -r abs_path; do
        [[ -z "${abs_path}" ]] && continue
        _log "  - ${abs_path}"
    done < "${STATE_FILE}"

    _log ""
    docker compose -f "${GENERATED_COMPOSE}" ps
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    [[ $# -eq 0 ]] && usage

    case "$1" in
        -h|--help) usage ;;
        --stop) _stop ;;
        --status) _status ;;
        *)
            local paths=()
            for arg in "$@"; do
                [[ -d "${arg}" ]] || _error "Directory not found: ${arg}"
                paths+=("${arg}")
            done
            [[ ${#paths[@]} -lt 1 ]] && _error "At least one path required"
            _start "${paths[@]}"
            ;;
    esac
}

main "$@"
